Document: gnujump
Title: Debian gnujump Manual
Author: <insert document author here>
Abstract: This manual describes what gnujump is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gnujump/gnujump.sgml.gz

Format: postscript
Files: /usr/share/doc/gnujump/gnujump.ps.gz

Format: text
Files: /usr/share/doc/gnujump/gnujump.text.gz

Format: HTML
Index: /usr/share/doc/gnujump/html/index.html
Files: /usr/share/doc/gnujump/html/*.html
